### ISSUE TITLE
Wrong seeding of thread-private RNGs in levelPops()

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#106]
In line 464 of aux.c the thread-private random number generators in levelPops() are seeded by the expression

    (int)gsl_rng_uniform(ran)*1e6

This is wrong, because the cast operates before the multiplication, giving a result which is always zero. Correct would be

    (int)(gsl_rng_uniform(ran)*1e6)

**Comment by imckstewart** [comment]
No, I hadn't noticed it. Well spotted (once again).
