### ISSUE TITLE
Getjbar() returns info only for species 0.

### ISSUE THREAD

**Issue by imckstewart** [lime-rt/lime#115]
The function `stateq()` is called separately for each species, but the species number is not passed to the call to `getjbar()`, which just returns values for species 0. Of course where there is only 1 species, this is harmless. For >1 species, ok even if `getjbar()` were fixed, the cross-excitation would still not be calculated properly, but returning `jbar` values from species 0 for species !=0 is simply wrong.

**Comment by tlunttil** [comment]
Yes, this and #114 are clearly serious bugs (especially #114 which probably segfaults if there's more than one species). The cross-excitation stuff is more of a detail. As I said in #21, a fully correctly functioning multispecies support would seem to need quite a bit of work; I'm not sure how important that feature is.
