### ISSUE TITLE
Wrong dSigma2 calculation

### ISSUE THREAD

**Issue by ParfenovS** [lime-rt/lime#120]
According to http://adsabs.harvard.edu/abs/2015A%26A...576A.105P
equation (8) given by Padovani et al. 2012 ( http://adsabs.harvard.edu/abs/2012A%26A...543A..16P  ) is wrong.
So, this line in sourcefunc.c
dSigma2 = maxp*g[pos].mol[ispec].dust[iline]*g[pos].mol[ispec].knu[iline]*(0.5*angle[2]*angle[2]-1./3.);
should be replaced by the following line:
dSigma2 = maxp*g[pos].mol[ispec].dust[iline]*g[pos].mol[ispec].knu[iline]*(angle[2]*angle[2]-2./3.);

**Comment by allegroLeiden** [comment]
Well spotted! I'll change that in my PR #117.

**Comment by smaret** [comment]
Fixed with e21f8e3.
