### ISSUE TITLE
Improving 'velocityspline'

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#124]
Currently the LOS-velocity-integrated lineshape along a Delaunay edge is calculated in function `velocityspline` as a sum of (a varying number of) Doppler-shifted Gaussians; the velocity is approximated as a fourth-degree interpolating polynomial that is constructed during grid initialisation.

I think that a better option would be to use a piece-wise linear approximation of velocity along the edges. In that case the velocity-integrated lineshape could be calculated analytically using error function. This method should be both faster (especially important if there is line blending, see the discussion about #99) and more accurate.

**Comment by allegroLeiden** [comment]
A good idea. Would you use a lookup table for the erf? I guess it does not have to be particularly accurate.

**Comment by tlunttil** [comment]
Yes, table look-up+interpolation for erf, I don't know how else to make it fast enough. I'm sure even a smallish, maybe a few thousand entries, table should be easily accurate enough.

**Comment by tlunttil** [comment]
A few thousand might already be an overkill, erf is a nicely behaving function.

**Comment by tlunttil** [comment]
I'll leave this issue open to remind us to maybe do this also in raytrace() at some point.
