### ISSUE TITLE
Problems in photon packet tracking

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#125]
There are some problems in Lime with photon packet tracking. These have been discussed in emails at least between @imckstewart and me and in Ian's LIME_algorithm.pdf, but I think it's better to raise the issues also here.

Firstly, there's a half-interval mis-match in assigning constant values of populations, temperature, etc. to Voronoi cells. To quote from Ian's pdf:
"The segment boundaries are mis-matched to the constant values of populations, temperatures
etc which are used for each segment calculation. In other words, segment i is taken to be the
whole edge between vertex i and vertex i+1; but the constant numbers used are those for vertex
i. Better would be to break the segment into two, the first part comprising the trailing half of
the edge connecting vertex i − 1 and vertex i, the second part being the leading half of edge i
to i + 1."

Secondly, no correction is made for the zig-zagging -- in general the 'true' direction of a ray is not aligned with the Delaunay edges, so a ray cannot follow the shortest straight path. This causes an over-estimation of the path length and, consequently, optical depth. 

Thirdly, also the calculation of Doppler shift doesn't take into account the possible difference between the ray direction and Delaunay edge. Here we have an additional problem in that currently only the projection of the velocity field along each Delaunay edge is stored, so it's not possible to calculate the projection along the ray direction.

Related to the last two issues: currently the next Delaunay edge to be followed is the one that is either the closest or the second closest to the ray direction (Monte Carloing which one of the two). I don't see why not always just choose the closest edge. Is there some reason for this randomisation?

There's an attempted fix of the first two issues in #83, but that PR is probably not compatible with some of Ian's much more extensive changes. I think it's better to scrap #83 and rewrite the fixes. There's also some sort of fix to the third problem in the linepol version, but it too will need to be rewritten.

**Comment by imckstewart** [comment]
My guess, FWIW, about the reason for the edge randomization: in the current scheme, in which the original photon direction is the quantity to test the edges against, rather than the photon path, I'm guessing there would be edges (for a given photon origin) which would never be traversed without the dither. (This may be the case even with the dither, because I think there can be up to 3 edges directed into any given hemisphere from an internal point.) If and when we change the algorithm to the path-following one we discussed, this would no longer be the case.

**Comment by tlunttil** [comment]
Sorry, I'm not following. `inidir`is chosen uniformly randomly on a sphere, so it's certainly possible that one (or some, or even all but one) of the edges from the initial point is not taken. It don't see how dithering eliminates this possibility; I don't even see (at least immediately) why dithering would make it less likely. I don't necessarily consider possibly not following an edge a serious problem, though, and in any case, determining the best distribution of sample directions is a complicated problem.

What do you mean by 'up to 3 edges directed into any given hemisphere for an internal point'? Isn't it more like at least 3 edges? Or are we talking about completely different things?

**Comment by imckstewart** [comment]
I always get into trouble when I try to shoot geometry from the hip - of course you are right, there will usually be many more than 3 edges pointing into any given hemisphere, given that the average number of edges per vertex in 3D seems to be about 16. I guess I was thinking rather of the face directions of the Delaunay tetrahedra.

The point about some edges never being traversed for a given starting point remains however. Imagine it this way: we have a grid point (or vertex) V and an edge, somewhere off in the model, E. Of the two end points of E, let's name the one nearer V as VE. E makes a fixed angle to the radial vector connecting V with VE. Suppose now there is another edge, F, leading off from VE, which makes a smaller (indeed the smallest for all the edges from VE) angle to this radial vector. Without dithering, any photon which reaches VE will always leave it again via F and never via E. Indeed E will never get any fun unless it makes no more than the second-smallest angle to V-VE.

I'm not any more so sure though that a path-following algorithm would no longer benefit from the dither. If one is going to dither, though, all the forward-facing edges should get some chance, not just the top two.

**Comment by tlunttil** [comment]
Ok, I see what you mean. Personally, I'd leave all randomisation in the selection of `inidir`. For each ray we'd then calculate the radiation intensity. The best way would be doing accurate raytracing as is done for the image in function `traceray`, but for performance reasons this is currently not done (though I'm not entirely convinced that it would be infeasible). The Delaunay edges work as some sort of elaborate lookup-thingy for quickly approximating true raytracing. It seems to me that the best way would be to try to stay as close to the 'true' ray as possible (I believe this is what you mean by the path-following algorithm). I don't see why sometimes randomly choosing a point further from the ray would be a good idea.
