### ISSUE TITLE
Bad sequence of grid.mol mallocs

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#130]
Suppose the user requests 3 images, of type successively line, continuum, line (same molecule obviously but maybe they want a different angle or resolution view of it.). For image 0, `levelPops()` will be entered. This mallocs `grid.mol` to the number of species, then later (in the call to `molinit()`) mallocs `grid.mol.dust` and `.knu` to the number of lines in that species. For image 1, `continuumSetup()` is entered instead, which frees `grid.mol`, re-mallocs both this and `grid.mol.dust` etc to have size 1, and sets `grid.mol.pops` to NULL. All the hard work of solving the populations is thrown away.

You might say, well the worst effect of this is just to waste time, but since `popsdone` is not reset, for image 2 (the third, we're counting from zero :wink:), we don't enter `levelPops()` again, control just passes straight to `raytrace()`. This will cause a crash.

**Comment by allegroLeiden** [comment]
Stupid - of course this is not true for the call to sourceFunc_cont() within photon().

**Comment by tlunttil** [comment]
sourceFunc_cont() is also used in photon(), so the change to interpolation should be done there, too. I agree though that knu and dust (a very non-descriptive name again...) could just as well be interpolated on the fly. I made a similar comment in discussion about #81.

**Comment by tlunttil** [comment]
Why are levelPops and continuumSetup done inside the image raytracing loop in the first place? levelPops is only done (max) once, so why not just take it out of the loop?

It seems that integration of the dust continuum stuff to the rest of LIME is a bit, shall we say, fragile. Continuum part seems to use some structures that are really meant for line calculations, so it's apparently necessary to clear those of any line calculation data from previous images. Would it be very much work to remove all references to line data structures from continuum raytracing?

**Comment by allegroLeiden** [comment]
I plan to. :wink:

**Comment by smaret** [comment]
> Would it be very much work to remove all references to line data structures from continuum raytracing?

@tlunttil Can you open a new issue for it?

**Comment by tlunttil** [comment]
I'll probably open a new issue once I've looked at the code more closely so that I have some more concrete suggestions. It may take a while, and any changes would be post-1.6 anyway.

**Comment by allegroLeiden** [comment]
The dust and knu things (there may be other vectors for which this also applies) basically need to be dimensioned to the number of frequencies in play. For line images this is the sum over species of the number of lines per species; for a continuum image only 1 frequency is needed/relevant. The best way to avoid having to redimension these vectors might be just to split traceray into a line vs. a continuum version. That would have the added benefit of removing all the tests for doline within traceray.

As with most programming matters however there is not going to be a perfect solution.
