### ISSUE TITLE
.nmol never set for sink points when `par.lte_only`.

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#131]
Inside the raytracing algorithm, i.e. the block starting at line 111 of raytrace.c, `posn` can often be a sink point. Thus `sourceFunc_line()` and `sourceFunc_cont()` are called for sink points. These functions require values to be set of the grid-point attributes `nmol`, `binv`, `*pops`, `*knu`, `*dust`. Of these, all are given some value for all points for non-LTE, but `nmol` is not set for sink points for LTE.

**Comment by smaret** [comment]
Fixed with 84fff8b.
