### ISSUE TITLE
Wrong indexing of fine samples in velocityspline()

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#136]
In photon.c:velocityspline() (and the _lin() equivalent), samples of velocity (and then spectral line amplitude) are obtained at several locations along the edge between a grid point and its neighbour. The function first generates a coarsely-spaced grid of points, evenly spaced between the start and end of the edge, inclusive. For each of these coarse intervals it generates one or more 'fine' locations which is where it calculates the velocity using 'splines' (actually an interpolating polynomial). The fine locations are meant to be evenly spread throughout each coarse interval, but at the line

    sd=s1+(s2-s1)*((double)iaver-0.5)/(double)naver;

the `-0.5` ought to be `+0.5`. `s1` and `s2` are respectively the start and end of the coarse interval, and the loop variable `iaver` starts at 0. Thus the fine samples are shifted to too-small values.

This probably has only a small effect on the output.

**Comment by smaret** [comment]
I think that you're right. I guess that `iaver` stops at `naver-1`?

**Comment by allegroLeiden** [comment]
Yes.

**Comment by allegroLeiden** [comment]
I thought of Chebyshevs, which I tend to use a lot, but in this case I am not sure the advantage is worth it. I am pretty sure 4th order is too high anyway, and for lower orders the advantage of Chebyshevs becomes negligible.

**Comment by tlunttil** [comment]
Yep, the advantage of Chebyshev vs. uiniform s not that big, I think only a factor of 2/3 for 4th degree polys and I, too, am not too fond of the 4th degree interpolation in the first place. In fact I thought of using a piecewise linear approximation with 2-4 pieces on each edge with analytic integration instead of current sub-stepping algorithm. I might try that if I have time.

**Comment by allegroLeiden** [comment]
Yeah I like the linear->erf idea.
