### ISSUE TITLE
Bad syntax for internal links in documentation?

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#143]
E.g lines 126-127 in usermanual.rst are

    LimePackage/src/lime.h. LIME also accepts several
    :ref:`command line options <lime-options>`.

The text as viewed on github however looks like the attached screen shot.

![screenshot_2016-06-21_15-23-35](https://cloud.githubusercontent.com/assets/10670238/16231021/8a1795e4-37c4-11e6-8198-0dff54f162a4.png)

**Comment by allegroLeiden** [comment]
Maybe I am being extremely stupid here... but I had assumed that the whole point of using markdown for the rst docs was so they would be readable on github (if nowhere else). But the further down I go through usermanual.rst, the more errors I find. E.g. none of the information between lines 174 and 201 appears on the github page.

**Comment by smaret** [comment]
Github has only a limited support for RST file rendering. The user manual is meant to be read on [ReadTheDocs](http://lime.readthedocs.io). The link you mention [displays fine](http://lime.readthedocs.io/en/v1.5/usermanual.html#running-lime).

**Comment by allegroLeiden** [comment]
Ok... I thought there might be something I was forgetting. You can file this in the idiot box.
