### ISSUE TITLE
Wrong dopb in deltav calculation.

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#154]
deltav calculation on line 234 of photon.c uses only the microturbulent linewidth (not including thermal broadening). In cases where the thermal linewidth is not insignificant compared to the microturbulent one,  deltav currently samples the local lineprofile only near its centre and as a result, calculation of the lineprofile-averaged jbar is biased.

This seems to make quite a big difference in benchmark cases (see #147).

**Comment by ParfenovS** [comment]
dopb in photon.c is not a microturbulent width only. See line 44 in grid.c file.

**Comment by tlunttil** [comment]
Yeah, but line 234 of photon.c uses grid.dopb, not grid.mol.dopb. It's not a good idea to use the same name in two different places...

**Comment by ParfenovS** [comment]
Oh, now I see. Indeed.

**Comment by tlunttil** [comment]
Fixed in #153
