### ISSUE TITLE
Remove scaling of rays per point according to the number of neighbours?

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#160]
Currently the number of rays sent from each grid point is proportional to the number of its Delaynay neighbours. There doesn't seem to be any good reason for that and furthermore, the current implementation has some problems. Some buffers are scaled according to a (conservative) fixed estimate for the number of neighbours a grid point can have (essentially max_phot/ininphot). In most cases this just wastes memory, because the buffers are unnecessarily large. However, there is no check for the true number of neighbours, and it is, at least in theory, possible that the buffers are too small and the program crashes.

**Comment by allegroLeiden** [comment]
Agreed.

**Comment by tlunttil** [comment]
This was done in #191.
