### ISSUE TITLE
Problem finding fitsio.h

### ISSUE THREAD

**Issue by nje78757** [lime-rt/lime#166]
I have installed cfitsio and lime-1.6 on a LInux machine. 
When I try lime model.c in the example file,
it complains as follows:
In file included from /home/bettyjo/nje/LIME/lime-1.6/example/model.c:10:
/home/bettyjo/nje/LIME/lime-1.6/src/lime.h:35:20: error: fitsio.h: No such file or directory
make: *** [src/model.o] Error 1
The file fitsio.h does exist in cfitsio. 
If I copy it to lime-1.6/src, I still get the same error.

**Comment by tlunttil** [comment]
I'm not sure if I understand. Where is fitsio.h located on your computer? How did you install fitsio libraries?

**Comment by nje78757** [comment]
Hi,
I don't have root permission, so I installed lime-1.6 in a directory 
called LIME in my own area.
It complained about qhull and fitsio, so I downloaded those from the 
links on the LIME page
and put those in adjoining subdirectories of LIME, so lime-1.6, 
qhull-2015, and cfitsio are all
in subdirectories of LIME. I followed the README file to configure, 
make, make install.
The fitsio.h file is in cfitsio. When I run lime model.c in 
lime-1.6/example, it finds qhull OK, but
not fitsio.h. I tried copying fitsio.h to lime-1.6/src but it still does 
not find it.
I append the top part of the Makefile, which I do not understand. I have 
tried putting explicit paths into it, but it
does not seem to help.
Neal

# Makefile
# This file is part of LIME, the versatile line modeling engine
#
# Copyright (C) 2006-2014 Christian Brinch
# Copyright (C) 2015 The LIME development team

##
## Make sure to put the correct paths.
##
PREFIX  =  ${PATHTOLIME}

ifneq (,$(wildcard ${PREFIX}/lib/.))
     LIBS += -L${PREFIX}/lib
endif
ifneq (,$(wildcard ${HOME}/lib/.))
     LIBS += -L${HOME}/lib
endif
ifneq (,$(wildcard /opt/local/lib/.))
     LIBS += -L/opt/local/lib
endif
ifneq (,$(wildcard /sw/lib/.))
     LIBS += -L/sw/lib
endif
ifneq (,$(wildcard /usr/local/lib/.))
     LIBS += -L/usr/local/lib
endif


CPPFLAGS        = -I${PREFIX}/include \
                   -I${PREFIX}/src \
                   -I${HOME}/include \
                   -I/opt/local/include \
                   -I/sw//include \
                   ${EXTRACPPFLAGS}

ifdef OLD_QHULL
         QHULL   = qhull
         CPPFLAGS += -DOLD_QHULL
else
         QHULL   = qhullstatic
endif

ifdef OLD_FITSIO
         CPPFLAGS += -DOLD_FITSIO
endif

**Comment by ParfenovS** [comment]
In the Makefile, these lines:

ifdef OLD_FITSIO CPPFLAGS += -DOLD_FITSIO endif

mean that the code will look for fitsio.h file located in the cfitsio directory. With these lines the code will not find fitio.h in the src directory or in the root LIME directory.
You can try following (actually there is a number of different ways to solve the problem).
Create cfitsio directory in the src directory and put fitsio.h (and, probably, other cfitsio header files ) there.

**Comment by nje78757** [comment]
HI,
I tried that. Copied all the .h files from cfitsio directory into 
lime-1.6/src/cfitsio
and I get the same error.
You mentioned other ways?
Thanks,
Neal

**Comment by nje78757** [comment]
Never mind...
I added OLD_FITSIO = false to the Makefile and now it finds fitsio.h and 
runs.
the doc instructions led me to think that false was the default.
Thanks and sorry to bother you.
Neal

**Comment by ParfenovS** [comment]
Oh. I'm sorry. My bad.
Yes, the lines in the Makefile that I mentioned work only in the case if one set the OLD_FITSIO variable. By default this variable is not set so my answer wasn't correct.
