### ISSUE TITLE
Increasing optical depth before line-blending part in photon.c

### ISSUE THREAD

**Issue by ParfenovS** [lime-rt/lime#176]
expTau[iline] array in photon.c contains the optical depth integrated along the way from the initial to the current cell. It shouldn't contain the optical depth in the current cell when it is used to increase the intensity in the following code:
`mp[molI].phot[lineI+iphot*m[molI].nline]+=expTau[iline]*remnantSnu;` (line 315 in photon.c)
This is not true in the line-blending part where in line 346:
`mp[molI].phot[lineI+iphot*m[molI].nline]+=expTau[iline]*remnantSnu;`
expTau[iline] contains optical depth in the current cell which was added earlier in line 317.

This can be easily fixed by, for example, using an additional variable which accumulates the optical depth in the current cell for all blended lines.

**Comment by ParfenovS** [comment]
And there is almost the same problem in getjbar function in photon.c.

**Comment by tlunttil** [comment]
I can bake this one into #153, which does a number of things in photon.c anyway. However, even after fixing this there are still a few things that are not done exactly correctly in case of blended lines (I've added some comments in #153 about them). It seems to me that those problems are unlikely to have much of an effect, but fixing them looks to require some annoying tinkering.

**Comment by tlunttil** [comment]
@ParfenovS: I don't see the problem in getjbar(). Can you point to where exactly it is? tau and expTau are not accumulated in getjbar() as they are (wrongly) in photon().

**Comment by ParfenovS** [comment]
Lets assume that remnantSnu=0,
tau_i - optical depth of the i-th blend
I_in - incoming radiation.
If I understand correctly, the current getjbar version computes the intensity (not a mean intensity) as:

I = I_in * [ exp(-tau_1) + exp(-tau_2) + exp(-tau_3) + ... ]

I guess it should be computed actually in the following way:

I = I_in * exp(-tau_1 - tau_2 -tau_3 - ... )

**Comment by ParfenovS** [comment]
In other words, expTau should accumulate the optical depth of blended lines before jbar[lineI] will be increased on expTau*mp[molI].phot

**Comment by tlunttil** [comment]
Ok, I see. Actually now that I think of it, the whole remnantSnu thing with blended lines should be done differently.

**Comment by allegroLeiden** [comment]
I hope you guys know what you are doing, I haven't the time to dive back into this at the moment.
