### ISSUE TITLE
Possibly wrong calculation of knu

### ISSUE THREAD

**Issue by ParfenovS** [lime-rt/lime#178]
Since #58, there was an attempt to calculate the dust density more wisely. But still there are problems with these calculations.
The dust mass density can be computed with gas mass density through the dust-to-gas mass ratio. The gas mass density can be computed with:
mu_AMU_n_H,
where mu - mean molecular weight, AMU - atomic mass unit, n_H - hydrogen number density. In this formula, there always (at least while mu*AMU is fixed) should be the H number density but not the number density of H_2 or some other species.
In the current code version, the number density is potentially a sum of densities of different species but not the number density of atomic hydrogen. The correct value of dust density (and knu) can be obtained using dustWeights. But even in the example model, knu is underestimated by a factor of 2 because dustWeights=1.0 (it should be dustWeights=2.0).

**Comment by tlunttil** [comment]
Yeah, that 2.4 really shouldn't be hardwired in the code on line 178 of grid.c.

**Comment by tlunttil** [comment]
Though 2.4 is a more likely value for mu per H_2 than per hydrogen atom, so I guess in this case the example model calculates the dust opacity properly. But properly mu should be user-settable.

**Comment by ParfenovS** [comment]
> Though 2.4 is a more likely value for mu per H_2 than per hydrogen atom

No. It is per H atom. Mean molecular weight per H_2 can't be > 2 in the case of H2-dominated molecular gas.

**Comment by tlunttil** [comment]
I'm afraid I don't understand. Maybe we're talking about two different things. For example, gas with 90% (by number) H_2 and 10% He would have mean molecular weight (in AMUs) per H_2 molecule of (0.9*2+0.1*4)/0.9=2.44. Per H atom it would be (0.9*2+0.1*4)/(2*0.9)=1.22.

**Comment by ParfenovS** [comment]
Ok. I'm wrong that the example model is not correct in the sense of dustWeights. The gas mass density, rho, can be computed in two ways (n - the number density):
1) rho = mu_H2 * AMU * n(H_2)
2) rho = mu_p * AMU * [ n(H_2) + n(He) ]

mu_H2 = M / AMU / N(H_2) ~ 1.4 * M(H_2) / AMU / N(H_2) ~ 2.8,
where M - total gas mass, M(H_2) - total mass of H_2, N(H_2) - total number of H_2

mu_p = M / (N(H_2) + N(He)) ~ 2.3

So I just didn't realized why the code uses mu=2.3 while in the example model there is only H_2.

**Comment by tlunttil** [comment]
The current code isn't really 'wrong' in the sense that by adjusting dustweights the user can effectively set mu to whatever they want. However, the documentation could be clearer on what exactly `par->dustweights` does and on the fact that there's a hardwired 2.4 factor included (and whether that should be included by default is another question).

**Comment by allegroLeiden** [comment]
I finally got to look at this. Let me see if I understand. The quantity `gp[id].cont.knu` in the code is the alpha on the LHS of equ 5 in Brinch and Hogerheijde (2010), right? In which case it is a product of the opacity kappa and the dust mass density. Kappa is `kappa` in the code and the mass density is supposed to be this thing at line 180 in the current grid.c which contains the 2.4. Well, line 180 looks wrong to me, or at least 'evil'. Shouldn't the correct calculation for mass density be given by pseudo-code like the following:

```
    gasMassDensityAMUs = 0.0;
    for(di=0;di<par->numDensities;di++)
      gasMassDensityAMUs += gp[id].dens[di]*par->molMassAMUs[di];

    gasIIdust(gp[id].x[0],gp[id].x[1],gp[id].x[2],&gtd);
    gp[id].cont.knu = kappa*AMU*gasMassDensityAMUs/gtd;

```
I think @tlunttil has the right of it, that the 2.4 is the average mass of a 90%H_2 10% He mix.

**Comment by tlunttil** [comment]
In an ideal world that would work, however:
- molMassAMU is not given in LAMDA files for collision partners and hardwiring that kind of stuff in LIME feels stupid.
- I don't think He is always explicitly used as a coll. partner; many of the LAMDA files don't even give coll. coeffs for He so that would always be missing from gas mass calculation.

It's difficult to do this thing in a clean way. I'd maybe just remove multiplying by 2.4 (also at line 235) and explain in the documentation how to use par->dustWeights to do the thing.

BTW, if grid.c is modified, it would be good to add a comment in interpolateKappa that multiplication by 0.1 is to convert from cm^2/g in the file to internal units m^2/kg. There was a question (issue) about that a couple of months ago.

**Comment by allegroLeiden** [comment]
> it would be good to add a comment in interpolateKappa

Done.

> hardwiring that kind of stuff in LIME feels stupid.

Doesn't feel stupid to me (shrug) - considering we hard-wire in all sorts of other constants. If we add a facility for the user to include non-LAMDA coll pars we'd need another parameter for the gas masses.

> many of the LAMDA files don't even give coll. coeffs for He so that would always be missing from gas mass calculation.

But we have in 1.7 now explicitly decoupled the densities from any transition coefficients. With present Lime for example, a user can omit any mention of He (or any other coll par) from their moldatfiles yet still provide a density for He. In that case they would need to do something like
```
  par->collPartIds[0] = CP_H2;
  par->collPartIds[1] = CP_He;
```
They can do this and also still avoid using He in the abundance calculation by setting in addition
```
  par->nMolWeights[0] = 1.0;
  par->nMolWeights[1] = 0.0;
```
We could then abolish `par->dustWeights` altogether. Problem solved? That certainly seems a lot neater way to me.

**Comment by allegroLeiden** [comment]
I've just modified the documentation in 1.7 - we can pursue this in some later release.

**Comment by tlunttil** [comment]
With hardwiring the problem is taking all possibilities into account, as we've seen people modelling comets for example have strange wishes ;) Though maybe we'll just have to live with the fact that in some very unusual cases the user may need to modify the code.

You're right that it's no longer a problem if some coll. coeffs. are missing, so what you propose would work. But it's maybe better left for the next release after 1.7, if the plan is still to release tomorrow.

**Comment by allegroLeiden** [comment]
Yep. Totally fatigued with lime just at the moment.
