### ISSUE TITLE
Number of grid smoothing iterations

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#179]
The number of grid smoothing iterations is currently 20. I thought we reached consensus that 20 is too many, but apparently the change was never made in the code. Were there some second thoughts or did this one just fall through the cracks? @allegroLeiden

**Comment by allegroLeiden** [comment]
It is set in lime.h now, so relatively easy to hack. I have not bothered much about it myself because #93 will avoid the need to smooth altogether.

**Comment by tlunttil** [comment]
Ok, in that case it's probably not worth changing now.
