### ISSUE TITLE
Dust opacity calculation

### ISSUE THREAD

**Issue by lolMEvans** [lime-rt/lime#180]
I was wondering why when calculating the dust opacity, kappa, it is multiplied by 0.1 in interpolateKappa (line 137 in grid.c)? This gives kappa = 0.137g/cm^2 at 300GHz rather than 1.37g/cm^2 as is given for grains with thin ice mantles and coagulation at 10^6cm^−3 in Ossenkopf & Henning (1994).

**Comment by tlunttil** [comment]
I think it's there to change the units from cm^2/g in the table to m^2/kg, which is used internally in LIME.

**Comment by lolMEvans** [comment]
Ah of course I forgot about the unit conversion- thanks.

**Comment by tlunttil** [comment]
LIME could really use some more comments in the code. I'll try to remember to add a line there the next time I'm doing some changes.
