### ISSUE TITLE
Poor control of convergence

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#181]
Currently the number of global iterations in LIME is hardwired in lime.h to 16 and there is no checking whether the solution has converged by then. 

A problem linked to this is that the ray directions are not the same for each iteration. (There is also an extra source of randomness in multithreaded computations due to updating the level populations on the fly). This mixes the effects of Monte Carlo noise and iterations, which makes it very difficult to monitor convergence.

**Comment by allegroLeiden** [comment]
PR #92 includes a new parameter which allows the user to set the number of iterations. However of course I agree with the rest of the issues.

**Comment by allegroLeiden** [comment]
This was fixed in 1.7.
