### ISSUE TITLE
abundance of radiating species

### ISSUE THREAD

**Issue by migueldvb** [lime-rt/lime#186]
It is now possible to define the fractional abundance of a radiating species with respect to a weighted sum of the densities supplied for collisional partners. If this fractional abundance
is not constant througout the grid one needs to call the `density` function in the definition, for example:
```
void
abundance(double x, double y, double z, double *abundance){
  double *val;
  density(x,y,z,val);
  abundance[0] = f(x,y,z)/val[0];
}
```

Why not defining the density of the radiating species in the model file rather than a fractional value?

**Comment by allegroLeiden** [comment]
Personally I have no strong opinion about this either way. I would say it should be decided by consensus among Lime users. Unfortunately I suspect rather few of them read these pages... your idea of a mailing list would help here.

**Comment by tlunttil** [comment]
Isn't it much more common (at least in my field ISM/star formation) to talk about abundances relative to H_2 rather than absolute densities? So to me defining the abundance makes more sense

**Comment by tlunttil** [comment]
Neither @allegroLeiden nor me really use Lime, you see...

Maybe @smaret can comment.

**Comment by allegroLeiden** [comment]
Also @attilajuhasz, and my boss Michiel Hogerheijde, who I think is not signed up here.

**Comment by cleevesli** [comment]
As @tlunttil said, the most common convention in astrochemical models is
providing abundances relative to H2 (or sometimes total H). The abundances
are either prescribed by some kind of toy abundance model (power law within
some range) or interpolated over a pre-calculated chemical model, which is
what I do (or also calculated in LIME if I understand correctly, @smaret?).
I could just as easily provide total space density of the radiating species
but the abundance more directly tells you how much of your total available
O, C, N, etc go into a particular species. So if I see a water abundance of
around 2e-4 then I know that in normal circumstances that is almost all of
the available oxygen, while a space density doesn't directly tell you that
without knowing the H2 density.

L. Ilsedore Cleeves
Hubble Fellow, Harvard-Smithsonian Center for Astrophysics
60 Garden St, MS-51
Cambridge, MA 02138
1-706-237-8398
ilse.cleeves@cfa.harvard.edu
https://www.cfa.harvard.edu/~lcleeves/index.html

**Comment by allegroLeiden** [comment]
We could possibly provide the option - have it that if the user provides the present `abundance` function, this is used, but if not, then Lime looks for a `molDensity` function or similar. There are other ways to implement this, although I rather shrink from suggesting yet another user parameter to control the choice.

**Comment by migueldvb** [comment]
Thank you for you comments. Maybe it is not worth it too add another function for defining the density function since it looks like it will be not be very useful in general. For comet models there is no H2 and every molecule has its own spatial distribution depending on their photodisociation rates. However it is not a big issue to specify the fractional abundance with respect to the collisional partners.

**Comment by allegroLeiden** [comment]
I asked Michiel Hogerheijde here for his opinion on several of these issues. Since he is not on github I have to cut-and-paste his comments.

MH: Allowing definition of MolDensity or Abundance makes sense. Sometimes abundances are what you have. Sometime you may have abundances relative to some tracer (e.g. H) that is not equal to the collision partners that LIME uses (o-H2 and p-H2, e.g.). Expressing your abundances relative to what LIME expects may get the user confused, while calculating a MolDensity is what the user can easily do (since they understand their own standard well).

**Comment by migueldvb** [comment]
Having an optional abundance function, and otherwise using molDensity supplied by the user sounds very good.
