### ISSUE TITLE
Faulty 1st step in photon propagation

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#189]
At line 280 in the present photon.c the code executes `continue` to progress to the next grid point (the first grid point away from the photon start point). However this is done without setting `here` to this next grid point, so `here` is still set to the start point at the following (i.e. 2nd) pass through the propagation loop. One can fix this easily enough by inserting a line `here=there;` before the `continue` but this then exposes another potential problem in that theoretically the new `here` may be a sink point, at which the the propagation is supposed to terminate.

I will fix this in an imminent PR which has the main aim of changing the choice of next edge from that being closest (with some jitter) to the photon direction to that which keeps closest (ditto jitter) to the photon trajectory, while still going forward. What I propose to do is add the `here=there;` line as above but also move the test for `gp[here].sink` from the end of the loop to the beginning. As photon() is presently called this amounts to a surplus test for the first grid point, but it looks like a small cost to retain simplicity.

**Comment by tlunttil** [comment]
I remember that the test for sink points has been oscillating between the beginning and the end of the loop for a couple of times now and it has also changed between testing `gp[here].sink` and `gp[there].sink`. But I think we're nearing convergence ;)

**Comment by allegroLeiden** [comment]
Plus ça change...
