### ISSUE TITLE
collision partner IDs

### ISSUE THREAD

**Issue by migueldvb** [lime-rt/lime#192]
The user parameter `collPartIds` is used to match the densities of collisional partners with the rates listed in the LAMDA data file. I have collisional partners that are not one of the 7 species defined in LAMDA ("H2","p-H2","o-H2","electrons","H","He","H+") so I am reusing those IDs for matching the datafiles to the density values. It looks like this should work for any molecules when  `collPartIds` and `nMolWeights` are set but I may have missed something. Is there any reason why using different collisional partners from the valid LAMDA ones may break something?

**Comment by tlunttil** [comment]
As far as I know, it should work; for example, there's no special 'H2-ness' in collision partner ID 1. But @allegroLeiden knows these parts of code much better than I do.

**Comment by tlunttil** [comment]
Some of the messages do refer to the default LAMDA partner names, but that doesn't affect calculations.

**Comment by migueldvb** [comment]
That is what I thought, thanks!

**Comment by allegroLeiden** [comment]
Sorry not to comment before but I have been working pretty hard trying to recover from a multiple disk failure.

Technically I think this ought to work but I don't think it is a very elegant way to do things. I'll have a think about it when I have some time and see if I can't come up with a better way. We definitely ought to have a mechanism to accommodate users who don't want to be restricted to LAMDA.

**Comment by migueldvb** [comment]
Using `collPartIds` greater than 7 does not work at the moment because `readMolData` tries to match the collision partner with one of the LAMDA values.

**Comment by tlunttil** [comment]
As a quick fix, I think it would be enough if you change the value of `MAX_N_COLL_PART` in lime.h and add names for new collision partners to `*collpartnames[]` in molinit.c. But it's true that the hardcoded LAMDA stuff should be removed in future.

**Comment by migueldvb** [comment]
@tlunttil that is a good workaround.

**Comment by allegroLeiden** [comment]
Maybe we could allow the user to submit a list of names and default to LAMDA if it is not supplied?
