### ISSUE TITLE
Cell-following raytrace algorithm is not thread-safe

### ISSUE THREAD

**Issue by imckstewart** [lime-rt/lime#203]
When par->traceRayAlgorithm==1 the software makes use of an algorithm which finds the chain of Delaunay cells traversed by each ray then interpolates quantities of interest inside the cells to solve the RTE. I note with some chagrin however that I neglected to make this procedure thread-safe, and at least one user has had a crash during raytracing in parallel when this option was chosen.

I'll put a note in the documentation for now.

**Comment by tlunttil** [comment]
What breaks the thread-safety here?

**Comment by allegroLeiden** [comment]
Errrr... maybe it is after all? Working far too hastily at the moment. F**k deadlines. F**k unrealistic expectations. Oh yeah, merry xmas everybody. Woohoo, kind of.

**Comment by tlunttil** [comment]
I didn't immediately see anything, though I didn't look that carefully. I might take a closer look later today, but at least for the time being, the note in documentation should remain.

**Comment by allegroLeiden** [comment]
Found this problem - it was a variable I declared static in extractFace(). I'll push a fix in a day or two.

**Comment by allegroLeiden** [comment]
Closed by #208.
