### ISSUE TITLE
Mandatory functions required also for predefgrids?

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#217]
I'm not sure if this is a bug or a feature...

I tried @lolMEvans 's model from #150 to see if that problem has disappeared. However, the run terminates early because there are no density() etc. functions defined. Why should they be needed when using a predefgrid model? Or have I misunderstood what is meant by a predefgrid in LIME?

@allegroLeiden is probably the one who knows about this.

**Comment by allegroLeiden** [comment]
TBH I have not been assiduous in maintaining the predefgrid option. I'll overhaul it after the current set of additions/fixes, I promise.

**Comment by tlunttil** [comment]
> TBH I have not been assiduous in maintaining the predefgrid option

Neither have I and there's not even a test for it currently. Out of sight, out of mind...

**Comment by tlunttil** [comment]
There are also issues with input from fits files (and I think with restarts, too), which I had until now completely forgotten about. Functionally input from a fits file is the same as an ASCII pregrid, because velocity field is not available except at grid nodes. This means that the normal piece-wise linear vfac calculation in photon cannot be used and in raytracing. There should probably be some 'only node data available' flag, which is automatically set in these cases. Then needless (and impossible) validity checks for user defined functions can be bypassed and vfac calculation in photon() and image raytracing can automatically select safe versions.

**Comment by allegroLeiden** [comment]
I've tightened up the tests for the 'mandatory' functions now and in general the way they interact with the fits file input. Your suggestion for the raytracing to choose which routine to apply is a good one, but you know, later in the year I would like to think about moving to LIME-2.0 with a totally revamped param interface, lots of things that are now choices made mandatory, etc. With such a movement, a lot of these issues would go away. On the other hand this may in fact never happen, since I will be looking for a new job by that time. Alas, LIME faces another winter of indefinite length in which it is out of the hands of expert carers. ;)

**Comment by tlunttil** [comment]
I think I'll do 'something' about this; as far as I can tell, at the moment none of the read-model-from-file options work because they try to access velocity field information that is not available to them. Can't promise that the solution will be pretty...

**Comment by allegroLeiden** [comment]
What if you turn on traceRayAlgorithm and doInterpolateVels? You should then be able to import a model with velocities and avoid providing the function.

**Comment by tlunttil** [comment]
That's kinda what I meant: just making sure that these things are automatically selected (also using calcLineAmpLin in photon). As far as I can tell, it doesn't happen now automatically and due to some strange quirks it may not even be possible by a normal user in some cases.

**Comment by allegroLeiden** [comment]
I added a doInterpolateVels also to configInfo. Maybe you could replace the test for predefgrid in traceray() with a test for img.doInterpolateVels and have predefgrid set it. Something like that. With a little thought and planning it doesn't have to be too ugly.

Actually there are two related situations it might be as well to flag in configInfo: (A) that a velocity function is available, (B) that pre-calculated velocity values are available at the grid points. If B then we test for A (which carries the possibility of Lime exiting) only if the user has refused interpolation for all images (i.e. configInfo.doInterpolateVels==0). On the other hand img.doInterpolateVels would invoke interpolation (of different sorts) in both traceray() and traceray_smooth(). How about that?

**Comment by allegroLeiden** [comment]
Anyway I'll leave #220 open til Friday for anyone to comment, then merge it. That's all I have planned for the moment, I'll be working pretty hard on other stuff for a couple of weeks.

**Comment by tlunttil** [comment]
Sounds good to me.

BTW, the whole ascii predefgrid thing is an ugly kludge which I'd be happy to banish. However, I have a feeling that it may be something that users actually need.

**Comment by allegroLeiden** [comment]
I plan to write an ascii to fits (or hdf5) converter at some stage, which would at least allow us to shift this crappy predefgrid/popsin code out of Lime. I'd link gridio.c etc for that so there might not be a lot of coding involved.
