### ISSUE TITLE
Problem finding qhull

### ISSUE THREAD

**Issue by kaifuski** [lime-rt/lime#222]
I have a problem when I tried to test the file "model.c" using LIME. It looked like how it would have a problem with qhull. Before I had installed libqhull-dev, version 2012.1-5, from debian repositories.

The first time I attempted run the program it showed an error like this.
```
/usr/bin/ld: no se puede encontrar -lqhullstatic
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target '/home/jesus/Descargas/lime-master/lime_15305.x' failed
make: *** [/home/jesus/Descargas/lime-master/lime_15305.x] Error 1
```
The traduction of "no se puede encontrar" is "cannot find".
I tried to resolve the problem commenting the makefile in this way (lines 42,45,46,47):
```
#ifdef OLD_QHULL
     QHULL=qhull
     CPPFLAGS += -DOLD_QHULL
#else
#    QHULL=qhullstatic
#endif
```
With this, the program could run the first two steps (Building grid and  Smoothing grid) but then it showed this error.
`*** Error opening dust opacity data file!`
And also this.
```
jesus@asp14:~/Descargas/lime-master$ ./lime example/model.c
src/raytrace.c: In function ‘traceray_smooth’:
src/raytrace.c:733:29: warning: passing argument 2 of ‘doBaryInterpsVel’ from incompatible pointer type
       doBaryInterpsVel(DIM, vertexVels, edgeVels, edgeVertexIndices, entryCellBary, exitCellBary, doRay, rayVels);
                             ^
src/raytrace.c:382:6: note: expected ‘const double (*)[(sizetype)numDims]’ but argument is of type ‘double (*)[3]’
 void doBaryInterpsVel(const int numDims, const double vertexVels[][numDims], const double edgeVels[][numDims]\
      ^
src/raytrace.c:733:41: warning: passing argument 3 of ‘doBaryInterpsVel’ from incompatible pointer type
       doBaryInterpsVel(DIM, vertexVels, edgeVels, edgeVertexIndices, entryCellBary, exitCellBary, doRay, rayVels);
                                         ^
src/raytrace.c:382:6: note: expected ‘const double (*)[(sizetype)numDims]’ but argument is of type ‘double (*)[3]’
 void doBaryInterpsVel(const int numDims, const double vertexVels[][numDims], const double edgeVels[][numDims]\
      ^
src/raytrace.c:733:51: warning: passing argument 4 of ‘doBaryInterpsVel’ from incompatible pointer type
       doBaryInterpsVel(DIM, vertexVels, edgeVels, edgeVertexIndices, entryCellBary, exitCellBary, doRay, rayVels);
                                                   ^
src/raytrace.c:382:6: note: expected ‘const int (*)[2]’ but argument is of type ‘int (*)[2]’
 void doBaryInterpsVel(const int numDims, const double vertexVels[][numDims], const double edgeVels[][numDims]\
      ^
```

**Comment by tlunttil** [comment]
LIME uses by default static qhull library (don't know why), but static library doesn't seem to be included in most repos (not in ubuntu either). So you need to use the OLD_QHULL option. 

The error message isn't related to this in any way. The default model uses jena_thin_e6.tab dust opacity file, which you should find in /example. For some reason, LIME fails to find the file in your test.

You can ignore the compiler warnings. They'll be fixed eventually but they don't really break anything.

@allegroLeiden : I think function call at line 733 of raytrace.c should have explicit const double (*)[] casts (or remove constness from array arguments on line 382). const works a bit surprisingly in c sometimes...

**Comment by allegroLeiden** [comment]
The qhull stuff will get fixed (or go away) as soon as we set up a proper config file for LIME. This is pretty much my next thing to look at, but I am occupied with other work at the moment.

I'll look into the other 2 errors as soon as I can get to it. @kaifuski which version of LIME are you using?

**Comment by tlunttil** [comment]
@kaifuski : I noticed the command line in your comment. With the default model LIME searches for the dust data file in the current folder. So you should either copy the dust model file from lime-master/example/ to lime-master/ or run lime in lime-master/example as ../lime model.c

**Comment by tlunttil** [comment]
Those compiler warnings don't appear unless -pedantic is used starting with gcc 5 series (see https://gcc.gnu.org/gcc-5/changes.html, look for "To allow proper use of const qualifiers with multidimensional arrays"). I would just leave it as it is.

**Comment by kaifuski** [comment]
@allegroLeiden Version 1.7.2
@tlunttil Using your suggestion the program worked correctly only when I have commented the lines 42,45,46,47 from Makefile. If I do not comment the lines then the program show the same error message about lqhullstatic.

Also, I use gcc version 4.9.2

**Comment by tlunttil** [comment]
Yes, the default is to use the static library, which is apparently not included in most repos (as I said earlier, I don't know why the static version is used). So you have to edit the makefile (as you've done) or for example define environment variable OLD_QHULL so that dynamic qhull libraries are used. @allegroLeiden probably has some more user-friendly solution planned in the nearish future.

**Comment by SmirnGreg** [comment]
Hi! I am trying to install lime, and can't figure it out. 
1) qhull does not have `configure` anymore. I have used 
```bash
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/path/to/lime ..
```
to build it, and now I have
```bash
$ ls /path/to/lime/include
libqhull  libqhullcpp  libqhull_r
```

When I try to run lime, it crashes:
```bash
$ lime model.c
In file included from /path/to/lime/example/model.c:10:0:
/path/to/lime/src/lime.h:27:21: fatal error: qhull_a.h: No such file or directory
 #include <qhull_a.h>
                     ^
```
Could you please help me, and probably update the configure / readme for the future?
Many thanks in advance!

**Comment by allegroLeiden** [comment]
Dear Grigorii,

Thank you for your email.
Here at ALMA are looking into it.

I have cc'ed Daniel Harsono to this email since he's the expert on LIME.
Hopefully, he will respond to you soon.

Best regards,
Liz (on behalf of Allegro)

**Comment by danharsono** [comment]
Hi Grigorii,

Since you are using libqhull, that means that lime.h crashes in:
#ifdef OLD_QHULL
#include <qhull/qhull_a.h>
#else
#include <libqhull/qhull_a.h>
#endif

It should be <libqhull/qhull_a.h>.

Regards,
Daniel

**Comment by SmirnGreg** [comment]
> lime.h crashes in: #ifdef OLD_QHULL #include <qhull/qhull_a.h> #else #include <libqhull/qhull_a.h> #endif It should be <libqhull/qhull_a.h>. 

Hi Daniel,
thanks a lot for your reply! It runs now.

I just wanted to mention that in the current master f438c48, as well as in the latest release 1.9.5, this line is just 
```c
#include <gsl/gsl_linalg.h>
#include <qhull_a.h>
#include <fitsio.h>
```

Best,
Grigorii.
