### ISSUE TITLE
segfault when running Lime with electrons as only collision partner

### ISSUE THREAD

**Issue by gica3618** [lime-rt/lime#227]
I am trying to simulate (with version 1.7.2) carbon emission from a debris disk environment where electrons are the most important collision partners. I couldn't get it running, so I determined the minimum changes necessary to the model.c in the example folder that reproduce the error. The following two changes result in a segmentation fault:

- change par->moldatfile[0] to "c+.dat" or "c.dat"
- change par->collPartIds[0] to CP_e

I also changed img[i].trans to 0 (c+.dat contains only one transition), but anyway I think the error is produced before the image parameters become important.
When using CP_p_H2 instead of CP_e, no error occurs.
Is it possible to say why this error is produced?

**Comment by tlunttil** [comment]
I get "Error: No recognized collision partners read from file.", not segfault. Anyway, it seems that reading the moldatafile goes off the rails if a coll.partner is found in the moldatafile, but not used by the model.

@allegroLeiden : if block starting line 150 of molinit.c is only run if the current coll.partner is requested by the model. But if it's not run, the file reading goes completely out of sync. I think fscanf etc. around lines 188-217 should always be done (and results discarded if they're not needed) to ensure proper reading of LAMDA molecule data files.

**Comment by tlunttil** [comment]
@gica3618 : As a quick fix, you can edit the moldata file so that the collisional transition data with electrons comes as the first coll. data in the file; currently the first partner is read correctly.
[c+.dat.txt](https://github.com/lime-rt/lime/files/965179/c.dat.txt)

**Comment by allegroLeiden** [comment]
I'll have a look.

**Comment by tlunttil** [comment]
I could take a look at fixing this myself, tomorrow I'll be spending a couple of hours on a train with nothing much to do. Or do you have some PRs that will have an effect on this?

**Comment by allegroLeiden** [comment]
There are a few PRs and proto-PRs pending but nothing affecting molinit.c. Knock yourself out. :)

**Comment by allegroLeiden** [comment]
Part of this problem seems to be due to the fact that there is no file named `c.dat` in the LAMDA database - the relevant file is named `catom.dat`. If the moldat file is not available locally, LIME is supposed to look for it in LAMDA and downloads it via a socket connection. However if the file does not exist, what gets downloaded and written to the example subdirectory is the bit of html you see reporting a 404 error. This does not have the correct format for a moldat file, which crashes the code. It would obviously be a good idea to modify the code to trap and report such instances, but I am no expert in sockets, and a bit of a google reveals no obvious solution. The only way I can think of to do this is to check the contents of the written file for the 404 messages, which does not seem very robust. @tlunttil any suggestion?

**Comment by allegroLeiden** [comment]
I am actually not very keen on the code doing this silent downloading, there is no reason the user cannot obtain the files they need from LAMDA manually. The facility was in LIME when I took it over however so I guess the weight of tradition dictates that we retain it.

The whole file-reading operation could also be a lot more robust, but this would take a bit of painstaking work that nobody yet has had time or inclination to undertake. It has been enough of a job just disentangling the functionality.

**Comment by tlunttil** [comment]
Ah, ok. I manually downloaded the file.

Honestly, I'm not entirely sure if the whole silently trying to download LAMDA files feature is safe and needed.

**Comment by tlunttil** [comment]
Writing c code to parse text files such as LAMDA molecule data robustly is very annoying. I would be strongly inclined to sweeping the problem under the rug by just saying in the documentation that the data files must conform to the LAMDA format exactly. One tiny safeguard could be added: check that the first line of the file is !MOLECULE. That would at least detect if the moldatfile is not even trying to be a valid LAMDA file

As for the downloading (from a hardcoded IP...) part, I'd prefer that it be removed altogether, or at least made a user option that is disabled by default.

**Comment by allegroLeiden** [comment]
@tlunttil we seem to have been thinking simultaneously on similar lines. :)

**Comment by allegroLeiden** [comment]
Fixed in release 1.7.3.
