### ISSUE TITLE
Interpretation of doppler Parameter

### ISSUE THREAD

**Issue by richteague** [lime-rt/lime#236]
In the update to 1.7.x the interpretation of the doppler parameter (I believe) was changed but I'm struggling to interpret what we actually input. The manual states that this value is such that 'when added in quadrature to the thermal Doppler broadening specific to each molecule, this number gives the Doppler b-parameter which is the 1/e half-width of the line profile'.

If I understand this correctly then for a Gaussian line profile with standard deviation dV: sqrt(2) * dV = hypot(v_doppler, v_thermal). Running some slab models seems to confirm this. However, this then suggests that there's a minimum value, i.e. v_doppler >= v_thermal. If I run a model with v_doppler = 0.0 then I find, when fitting the resulting spectrum with a Gaussian and accounting for v_thermal, a non-zero v_nonthermal component, however this is not (as far as I can tell) related to this limit. What is going on here? I'm trying to work through the code but hopefully someone more familiar with the intricacies can chime in.

**Comment by tlunttil** [comment]
So in a static, isothermal, optically thin model with "doppler" (i.e., microturbulence) set to zero, the resulting lines are not just thermally broadened Gaussians? That doesn't sound right. Do you have an example model that I could look at?

**Comment by richteague** [comment]
Yes, exactly. I have the models (for CS) and the resulting .ds files here: https://www.dropbox.com/sh/bocuqhti9z2fnq6/AAB_UDUrGpKTgmV21f8y8oTEa?dl=0

You can also find a Jupyter Notebook of my trying to explain my reasoning here: http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/y0j1zega2bcgf5v/LineWidths.ipynb

Basically I am confused as to how to implement a constant X m/s microturbulence value to models.

**Comment by tlunttil** [comment]
Thanks, I'll have look. I don't immediately see why there would be some kind of built-in lower limit for microturbulence (also, "doppler" is not a very descriptive name for that...).

**Comment by tlunttil** [comment]
Spectral resolution is a bit low for the "no turbulence" case, so that LIME profile isn't very Gaussian-looking. That could cause some weirdness in the fitting. Do the results stay the same if you use velocity resolution of, say, 10 m/s instead of 30? Unfortunately I can't test that myself with the computer I'm currently on.

**Comment by richteague** [comment]
I've run it with a resolution of 3 m/s and they remain the same. I've over-plotted the Gaussian fits to the lines too.

[trans_32.pdf](https://github.com/lime-rt/lime/files/1055642/trans_32.pdf)
[trans_54.pdf](https://github.com/lime-rt/lime/files/1055640/trans_54.pdf)
[trans_76.pdf](https://github.com/lime-rt/lime/files/1055641/trans_76.pdf)

**Comment by tlunttil** [comment]
Actually it looks like the thermal line width is a just bit too large rather than a problem with the microturbulence. I wonder if there's a typo in some constant somewhere...

**Comment by tlunttil** [comment]
I can't find a bug in LIME related to this. I suspect this may be just some general numerical inaccuracy - you wouldn't necessarily expect the fitting to reproduce exactly what was in the model. In any case, the difference seems to be very small. For example, in your examples the 'residual Doppler' of <2 m/s in 'no microturbulence' case has the same effect on the total linewidth as changing the kinetic temperature from 25 K to about 25.01 K.

As for how the Doppler parameter should be interpreted: it's meant to be the 1D Doppler width (i.e., sqrt(2) times the 1D standard deviation) due to unresolved turbulence in the model. Not the most intuitive parameter, but in models it usually works as a kind of fudge factor anyway...

Maybe @allegroLeiden has something to add?

**Comment by richteague** [comment]
I don't think that I explained my issue very clearly, or maybe I I'm just completely lost in the numbers!

So, I have three models, all with a gas temperature of 25K and a column density such that they're optically thin. I include a doppler value of 1000 m/s, 100 m/s and 0 m/s in the three models. From these models I then measure the line width by fitting a Gaussian profile (this is the standard deviation of the line). The fits are good and reproduce the line with accuracies << 1%.

With this linewidth, dV, I can then calculate an 'effective' temperature, describing the temperature required to produce a line with that given width using dV = sqrt(2kT/m) where m = 44m_p for CS. For the two models with doppler > 0, I get T > 25, however for the model with no doppler value, I get T = 13K, lower than the gas temperature.

Furthermore, I can calculate the non-thermal broadening for the two models with doppler > 0 with vturb = sqrt(dV^2 - vtherm(25K)^2). Doing this I find vturb ~ 700 m/s for the doppler value of 1000 m/s and vturb ~ 20 m/s for the doppler value of 100 m/s. These don't seem to be a simple scaling of the doppler values as I'd have thought.

**Comment by tlunttil** [comment]
> With this linewidth, dV, I can then calculate an 'effective' temperature, describing the temperature required to produce a line with that given width using dV = sqrt(2kT/m) where m = 44m_p for CS. For the two models with doppler > 0, I get T > 25, however for the model with no doppler value, I get T = 13K, lower than the gas temperature.

Aren't you mixing up the Doppler parameter and std. deviation here? Your fitted sigma (std. deviation) is 69 m/s, which corresponds to sqrt(2)*69~=97m/s Doppler parameter.

**Comment by richteague** [comment]
Ah ok, gotcha. So to clarify, sqrt(2kT/m) gives the thermal Doppler-width, not the thermal standard deviation?

**Comment by tlunttil** [comment]
Yes, see for example http://jila.colorado.edu/~pja/astr3730/lecture09.pdf or http://www-star.st-and.ac.uk/~kw25/teaching/nebulae/lecture08_linewidths.pdf

**Comment by richteague** [comment]
Thanks for clearing this up!

**Comment by allegroLeiden** [comment]
Ha, this is the kind of issue I like - it clears itself up before I get to it.
