### ISSUE TITLE
Error when restarting from previous populations

### ISSUE THREAD

**Issue by christianbrinch** [lime-rt/lime#247]
Using the par->restart option gives the error "Cannot normalize the grid-point number density function."

**Comment by christianbrinch** [comment]
It seems that there are calculations in aux.c that are skipped if par->restart is set, but which are needed lated in parseInput. Indeed, this seems to be a bug.

**Comment by christianbrinch** [comment]
Also molInit is called if par->restart is set. It shouldn't be.

**Comment by allegroLeiden** [comment]
Which version?

**Comment by christianbrinch** [comment]
1.7.3.

**Comment by allegroLeiden** [comment]
Latest is 1.8.1. I addressed these loose ends with ->restart etc at some point before 1.8.

**Comment by christianbrinch** [comment]
I'll try the new version then.

**Comment by christianbrinch** [comment]
Yeah it works in 1.8.1. 
Please don't remove the restart option. It is very useful for comparing the ray-tracer to older versions. It shouldn't be a problem to keep it in as a feature.

**Comment by allegroLeiden** [comment]
I plan to sharply reduce the amount of time I spend on Lime after the CASA-interface release at the end of next month, so any reformation of it probably won't happen on my watch, but I am very much in favour in shall we say an academic sense in a major pruning of the various overlapping and tangled options. I added a separate task `gridconvert` with its own makefile target for the express purpose of translating the pregrid and restart file formats into the new, much more comprehensive and portable fits/hdf5 format. This would allow these options to be dropped from Lime.
