### ISSUE TITLE
Signal-to-noise ratio of level populations

### ISSUE THREAD

**Issue by ParfenovS** [lime-rt/lime#260]
In solver.c file, the line 1095 corresponding to eq. 15 from Brinch & Hogerheijde (2010):
stat[id].sigma[ilev]=sqrt(stat[id].sigma[ilev])/5.;

should be replaced by 

stat[id].sigma[ilev]=sqrt(stat[id].sigma[ilev] / 5.);

**Comment by allegroLeiden** [comment]
Closed in present master track.
