### ISSUE TITLE
LIME fails when using molNumDensity without nMolWeights

### ISSUE THREAD

**Issue by gica3618** [lime-rt/lime#265]
If I understand the user manual correctly, the molNumDensity function that the user can define in the model.c specifies the number densities of the radiating species directly. In other words, rather than being defined relative to the density of the colliders, with molNumDensity one can define the number densities of the radiating species in an absolute way. Therefore, defining nMolWeights should not be necessary. Still, LIME exits with "No H2 collision partner, and user didn't set par.nMolWeights." if one uses a collision partner different from H2.
As an example to reproduce the behaviour, I modified the default model.c to compute excitation of carbon by electrons, specifying the density of carbon directly using molNumDensity while at the same time not defining nMolWeights. See attached file [model.txt](https://github.com/lime-rt/lime/files/2074077/model.txt)
A similar error occurs if one uses the abundance function rather than molNumDensity, but with a collider different from H2, and without defining nMolWeights. In this situation, I would again expect that nMolWeights is not necessary, since there is only one collision partner, so its weight should be 1.
I am using LIME 1.9.1.

**Comment by allegroLeiden** [comment]
Hi, I'll try to have a look at this next week.

**Comment by allegroLeiden** [comment]
Closed in release 1.9.4.
