### ISSUE TITLE
IR pumping issue

### ISSUE THREAD

**Issue by mcordiner** [lime-rt/lime#269]
I have found that in version 1.9.2, when a list of pumping rates is supplied via the par->girdatfile, the resulting image is corrupted (can have inf values), and the code exits with a seg fault immediately after writing the fits file. An error message is given from glibc: "double free or corruption", so I suspect something iffy is happening with the memory handling?  Apparently the IR pumping was working properly in version 1.8.2, so a recent update may have broken it.

**Comment by allegroLeiden** [comment]
Can you post a model file + girdatfile so I can have a quick check?

**Comment by mcordiner** [comment]
I have emailed a test model. In the mean time, I am trying to go back to using 1.8.2 (last known working version). Unfortunately I haven't got ncurses installed (don't get me started about IT support around here)... is there an easy way of compiling without it? I note that in 1.9.2, all that's needed is to use the -n option, but that doesn't work in 1.8.2 as it still looks for curses.h.

**Comment by mcordiner** [comment]
I have tried 1.8.2 and reproduce the same errors as above. The image is corrupt if par->girdatfile is given when using LTE mode. However, in NLTE mode the output looks OK. I've contacted Miguel to see if I'm doing something wrong with the input files.

**Comment by allegroLeiden** [comment]
Ok, the problem is that your girdat file uses a C convention for the level numbering: i.e. starting at 0 and ending at nlev-1. As with the moldat file, the convention LIME expects is start at 1, end at nlev. I think the only thing I can do is add a trap for this sort of error - that would stop the code seg faulting, and also provide some diagnosis.

**Comment by mcordiner** [comment]
Thanks a lot for fixing that. Apparently the input format for the pumping file changed sometime between version 1.8 and 1.9!
