### ISSUE TITLE
segmentation fault when using molNumDensity without nMolWeights

### ISSUE THREAD

**Issue by gica3618** [lime-rt/lime#272]
Thanks for fixing issue #265. I still get a segmentation fault with the new version 1.9.4 though, when using molNumDensity without specifying nMolWeights. To illustrate, I took the model.c from the example folder. I replace the abundance function by a molNumDensity function and I comment out nMolWeights. This results in a segmentation fault, although nMolWeights should not be necessary if molNumDensity is defined. See attached [minimum_example_model.txt](https://github.com/lime-rt/lime/files/2268661/minimum_example_model.txt).
Interestingly, if I also comment out par->outputfile, the program runs fine.

**Comment by allegroLeiden** [comment]
Ok, I'll have a look.

**Comment by allegroLeiden** [comment]
Ok, I reproduce the error.

**Comment by allegroLeiden** [comment]
I grok it. Patch on the way.

BTW I recommend commenting out outputfile, binoutputfile and gridfile in any case. I've done this in the default model file now.

**Comment by allegroLeiden** [comment]
Closed by 1.9.5.
