### ISSUE TITLE
Some funny pixel values in output cube for small model

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#36]
Where the model is an object of the typical size of a comet, the output FITS cube contains many pixels with anomalous values. A bit of checking indicates that the culprit is line 54 of raytrace.c, where the code is testing the distance to the next cell wall. If this distance is less than the hard-wired value of 1e4 m, the photon is not processed any further.

Theoretically one could require that the distance be simply >0. However, numerical rounding errors can render imprecise results which are pure in a geometric sense. It is possible to arrive at a slightly positive distance to a cell wall which is in fact behind the present location of the photon. Hence the safety factor of 1e4, to exclude such borderline cases. This is adequate for an object significantly larger than 1 AU but causes problems for smaller objects, where the grid cells are proportionately smaller. A quick fix where the 1e4 is replaced by a factor scaled to the minimum grid size seems to work, but a more robust solution would be preferred.

**Comment by allegroLeiden** [comment]
Damn, I cannot figure out how to label this as a bug.

**Comment by smaret** [comment]
Fixed with 515fec08927ce15b3b979682ec53eba29d28fe84
