### ISSUE TITLE
Wrong random algorithm

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#40]
In the function buildGrid() of grid.c, initial grid points (i.e. before their further selection by the criterion of density weighting) are chosen at random, with a random distribution which depends on the value of the 'sampling' parameter of the inputPars structure. If sampling==0, a distribution function is chosen which seems to have been intended to generate points whose radial vectors are evenly distributed over a sphere. However, this is not the actual result. Choosing an even distribution of the polar phi angle between 0 and pi will instead result in points which have a higher density towards the positive and negative Z axes. The correct algorithm is rather to choose a Z coordinate which is evenly distributed between -R and R (where R is the model radius), similar to the algorithm in function photon().

**Comment by allegroLeiden** [comment]
This doesn't seem to make any visible difference in the image cube at vel==0 when img[0].theta is set to PI/2 in model.c. I had expected that it would.

**Comment by smaret** [comment]
Could you please document this new option in the user manual? The manual (in RST format) is now included in the repository.

**Comment by allegroLeiden** [comment]
Sure, will do. In any case I plan to go through the doco pretty carefully before the next release.

**Comment by smaret** [comment]
Documentation updated with fe211ea275bd12cf4b59bd3cfc9c0256df0b01b1.
