### ISSUE TITLE
Missing <ieee754.h> header file on MacOSX

### ISSUE THREAD

**Issue by smaret** [lime-rt/lime#48]
This header file is not present on MacOSX (but I am pretty sure that it conforms to IEEE754 standard), so the compilation fails.

**Comment by smaret** [comment]
@imckstewart Please accept the invitation to the lime-rt group so I can assign this issue to you :-)

**Comment by allegroLeiden** [comment]
Should be fixed by 5f5ad51.

**Comment by smaret** [comment]
Thanks!
