### ISSUE TITLE
Testing IEEE 754 compliance

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#49]
The FastExp function added in f0ba799 relies on floating-point numbers adhering to the bit pattern laid out in IEEE 754. Most processors seem to adhere to that these days, but still, it would be good to implement some sort of test to confirm compliance.

**Comment by smaret** [comment]
According to the [Autoconf documentation](http://www.gnu.org/software/autoconf/manual/autoconf.html#Floating-Point-Portability):
> Almost all modern systems use IEEE-754 floating point, and it is safe to assume IEEE-754 in most portable code these days.

**Comment by smaret** [comment]
I'm closing this as "won't fix" for the moment. Feel free to re-open it if you want to implement such a test at some point. According to the Autoconf documentation, I'm not sure that it is really needed though.

**Comment by imckstewart** [comment]
Ok.
