### ISSUE TITLE
Incorrect relation of dust to densities

### ISSUE THREAD

**Issue by allegroLeiden** [lime-rt/lime#58]
At (currently) line 69 of molinit.c the variable g[id].mol[s].knu[iline] is calculated. According to Michiel Hogerheijde, it is incorrect (or at least, leads potentially to an error in certain cirumstances) to derive this value from the density of the 0th collision partner as is currently done. However, it is not simply as simple as summing the densities of all coll partners, since some (I am told) play a greater role than others. Some thought (and discussion with the astronomers) needs to go into amending this. It is a bit late for the 1.5 release, but MH is happy to see it in a subsequent patch.

**Comment by smaret** [comment]
I agree with Michiel. However, [as far as git remembers (Dec 2011)](https://github.com/lime-rt/lime/blob/52572a0254d1e917592b5cc25f0e912d8b47002b/src/molinit.c#L67), it has always been computed in this fashion in LIME. So this can probably wait for another release.

**Comment by imckstewart** [comment]
Absolutely!

**Comment by smaret** [comment]
Fixed with #128.
