### ISSUE TITLE
Angles in continuum polarisation source function

### ISSUE THREAD

**Issue by attilajuhasz** [lime-rt/lime#68]
I have a bit of a trouble understanding how the angles gamma and psi are calculated in the polarisation part of the continuum source function. My understanding is that gamma is the angle between the magnetic field (B) and the plane of the sky/image, while psi is the position angle of the magnetic field projected into the image plane (i.e. the angle between the direction of North in the image plane and the projected B-vector). The `sourceFunc_pol()` and `stokesangles()` functions consistently use a variable name `incl` to describe the orientation of the model/source. The essence of my question is: how are gamma and psi calculated in the polarisation module and what is the meaning of `incl` in the source function? From the usage of `incl` within the functions I'm guessing it should be the inclination angle. However in the raytracer it is `image.theta` that is passed to the polarisation source function and `image.theta` is equivalent of the inclination if and only if `image.phi` is zero. Also why is there only a single angle in the polarisation module to describe the source orientation as, to my understanding, psi depends on the position angle of the source, i.e. to calculate both gamma and psi the source orientation has to be described by two angles.

**Comment by allegroLeiden** [comment]
I'm looking at this and I agree that the angle specification sent to stokesangles() is inadequate. I'm also wondering why the polarization fraction is hard-wired to 0.15. Going to ask Michiel about it.
