### ISSUE TITLE
Raytracing progress bar appears to be broken

### ISSUE THREAD

**Issue by christianbrinch** [lime-rt/lime#69]
The progress bar used to track the ray-tracing progress. With version 1.5 it seems to stay at 0 until the ray-tracing is done (and then jump to 100%). 
I have only tried continuum ray-tracing so far, so I don't know if this bug also affects line ray-tracing too.

**Comment by smaret** [comment]
I confirm that the bugs also affects the line ray-tracing.

@imckstewart: would you mind having a look at this?

**Comment by allegroLeiden** [comment]
Fixed by 18bf031, branch message_fixes.
