### ISSUE TITLE
Undefined 'FastExp' function warning

### ISSUE THREAD

**Issue by smaret** [lime-rt/lime#74]
LIME gives the following warning during the compilation with gcc 5.2.0:

```
In file included from src/aux.c:10:0:
src/lime.h:250:15: warning: inline function 'FastExp' declared but never defined
 inline double FastExp(const float negarg);
```

**Comment by tlunttil** [comment]
gcc 5.2.0 has changed to a different default mode (-std=gnu11 instead of -std=gnu89), so inline semantics have changed. I'd just remove explicit inlining. If it's worth doing, it's probably done by the compiler automatically when compiled with -O3.

**Comment by kpolsen** [comment]
Hi! I got the same warning - is it a problem? Or can we sleep at night? Also, I get this warning:
```
 In function 'greetings_parallel':
    warning: type of 'numThreads' defaults to 'int' [-Wimplicit-int]
    greetings_parallel(numThreads){ 
```

**Comment by allegroLeiden** [comment]
Hi kpolsen, sorry it has taken 6 months to comment - such is the pace of lime development sometimes! This was my bad and I will fix it in the next batch of minor bug fix PRs I make. No, it isn't a problem.

**Comment by allegroLeiden** [comment]
Just looking at this - I'm wondering if we implemented it properly in the first place. FastExp is pretty big for an inline function, and it is used in 2 modules, but defined not in a header file as recommended but in a third, which is thus only accessible at the linking stage. I guess I'll try removing the inline as @tlunttil recommends and see if it makes a noticeable speed difference.

**Comment by tlunttil** [comment]
I doubt it was ever inlined, I don't think gcc would do link-time optimization without specific switches. I tried at some point moving FastExp and a couple of other small, often used functions (I think they were the various sourceFunc*) to lime.h so they could be inlined and I got maybe 5 to 10 % speedup. Unfortunately I seem to have lost the code with the changes somewhere...

**Comment by imckstewart** [comment]
Probably easy enough to reinstate. I slimmed down the sourceFunc* thingies a bit in my latest PR, but there is more work on them needed, which however can only really be done after we rearrange the grid memory. So it all had better wait til after the next release I guess.
