### ISSUE TITLE
Density calculation is incorrect when the first collision partner is not molecular hydrogen

### ISSUE THREAD

**Issue by kpolsen** [lime-rt/lime#86]
Hey there,

I'm trying to simulate [CII] line emission with LIME, and can't see a line profile!

So far, I only made the following edits to the example model, model.c, that comes with LIME:

hco+@xpol.dat -> CII.dat (see below)
img[0].unit			    = 0 -> 1
abundance[0] = 1.e-9 -> 1.4e-4 (in this case the CII/H2 ratio right? Set to be very high here, equal to the solar [C/H]/2 ratio)
abundance[0] = 50 (i.e. a constant Tk rather than one that varies with R)

For simplicity, I've only considered para-H2 molecules as collisional partners (even though [CII] can also be excited by collisions with electrons, HI and orto-H2). For that purpose, I reduced the LAMDA data file to: 
-------------------   CII.dat   ---------------------------
!MOLECULE
C+ (atomic ion)
!MOLECULAR WEIGHT
12.0
!NUMBER OF ENERGY LEVELS
2
!LEVEL + ENERGIES(cm^-1) + WEIGHT + J
    1     0.000000000   2.0     0.5  ! 2P
    2    63.395087      4.0     1.5  ! 2P
!NUMBER OF RADIATIVE TRANSITIONS
1
!TRANS + UP + LOW + EINSTEINA(s^-1) + FREQ(GHz) + E_u(K)
    1     2     1  2.300E-06        1900.5369        91.21
!NUMBER OF COLL PARTNERS
1
!COLLISIONS BETWEEN
2 C+ + pH2  ! thermal H2 J=0 and J=2, cf Wiesenfeld & Goldsmith 2014)
!NUMBER OF COLL TRANS
1
!NUMBER OF COLL TEMPS
7
!COLL TEMPS
   10.0   20.0   50.0  100.0  200.0  300.0  500.0 
!TRANS + UP + LOW + COLLRATES(cm^3 s^-1)
    1     2     1  4.36E-10 4.53E-10 4.63E-10 4.72E-10 5.13E-10 5.55E-10 6.01E-10
-------------------   CII.dat   ---------------------------

And the line profile that comes out is almost constant across all velocity bins!:

![cii1](https://cloud.githubusercontent.com/assets/13789517/11155755/bca071de-8a04-11e5-91b7-22a25de60dd0.png)

I must be doing something stupid. Hoping someone has time to help me out!

**Comment by imckstewart** [comment]
Hi, I'm chasing up a couple of other bugs at the mo, but I'll try to have a look at this in the next few days (if no-one else gets there first).

**Comment by kpolsen** [comment]
Thanks a lot, looking forward to hearing back from you.

**Comment by ParfenovS** [comment]
Hello! I'm not from the LIME developing team but I can help you. To solve your problem you just need to change the collisional partner id in your CII.dat file. In other words you should replace this section:

!COLLISIONS BETWEEN
2 C+ + pH2 ! thermal H2 J=0 and J=2, cf Wiesenfeld & Goldsmith 2014)
!NUMBER OF COLL TRANS

by the following section:

!COLLISIONS BETWEEN
1 C+ + pH2 ! thermal H2 J=0 and J=2, cf Wiesenfeld & Goldsmith 2014)
!NUMBER OF COLL TRANS

This will not affect the accuracy and correctness of results.

**Comment by ParfenovS** [comment]
The problem itself is that the LIME code can not handle properly the situation when there is only one collision partner and it is not H2. If the collison partner is para- or ortho-H2 the code will not compute molecular density. I will create pull reaquest with the solution for this problem.

**Comment by imckstewart** [comment]
There's not really an official team, Sergey. I guess anybody who 
contributes code is self-elected. :)

In the New Year we ought to organize a telecon with all interested 
parties to discuss future directions.

Cheers Ian.


On 2015-12-10 17:10, Parfenov Sergey wrote:
> Hello! I'm not from the LIME developing team but I can help you. To
> solve your problem you just need to change the collisional partner id
> in your CII.dat file. In other words you should replace this section:
> 
> !COLLISIONS BETWEEN
>  2 C+ + pH2 ! thermal H2 J=0 and J=2, cf Wiesenfeld & Goldsmith 2014)
>  !NUMBER OF COLL TRANS
> 
> by the following section:
> 
> !COLLISIONS BETWEEN
>  1 C+ + pH2 ! thermal H2 J=0 and J=2, cf Wiesenfeld & Goldsmith 2014)
>  !NUMBER OF COLL TRANS
> 
> This will not affect the accuracy and correctness of results.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/lime-rt/lime/issues/86#issuecomment-163672521

-- 
--------------------------------------------------------------------
Ian Stewart, room 536  | Tel: +31 (0)71 527 8411
Sterrewacht Leiden     | Fax:
P.O. Box 9513          | Web: http://home.strw.leidenuniv.nl/~ims/
NL-2300 RA  Leiden     | Cell: +49 (0)174 168 5467
The Netherlands        | Mail: ims@strw.leidenuniv.nl
--------------------------------------------------------------------

**Comment by kpolsen** [comment]
Hi again, 

Thanks for the solution @ParfenovS , by making that change to the CII.dat file (as well as deleting the other collision partners for the time being and setting !NUMBER OF COLL PARTNERS to 1) we actually get a line profile now!

![cii_line_profile_gmc_0](https://cloud.githubusercontent.com/assets/13789517/12195430/653677bc-b5f7-11e5-85f7-4935f51fed17.png)


We are still checking whether the integrated [CII] luminosities are also as expected, and I will try to keep you updated on that.

**Comment by imckstewart** [comment]
Hello Sergey,

I just raised as an 'issue' that it would be good to have a 
teleconference of developers to discuss the future of lime. If you are 
interested in taking part, please have a look at the text of the issue.

Cheers Ian.

-- 
--------------------------------------------------------------------
Ian Stewart, room 536  | Tel: +31 (0)71 527 8411
Sterrewacht Leiden     | Fax:
P.O. Box 9513          | Web: http://home.strw.leidenuniv.nl/~ims/
NL-2300 RA  Leiden     | Cell: +49 (0)174 168 5467
The Netherlands        | Mail: ims@strw.leidenuniv.nl
--------------------------------------------------------------------

**Comment by smaret** [comment]
Note that with Sergey's fix, you must give the C abundance with respect to the first collider number density (p-H2 in your case). This is fine if H2 is mostly in para form, but this may lead to incorrect results if some of the H2 is ortho form.

**Comment by smaret** [comment]
Fixed with #128.
