### ISSUE TITLE
Example model output

### ISSUE THREAD

**Issue by GaryFuller** [lime-rt/lime#88]
Hi, I have installed LIME and run the example which comes with the package which is an infalling envelope. The spectra in the output image have a redshifted peak which is stronger than the blueshifted peak. This is the opposite of what you expect from an infalling envelope. Any thoughts about what is happening?

**Comment by imckstewart** [comment]
Hi Gary, this is a known issue offline, though nobody has yet raised it here. This looks a little bit like a simple sign error in the way lime processes velocities, but my own view is that there *was* a sign error in lime prior to the 1.5 release (see closed issue #38), which is now fixed, but which was masking and partially compensating a deeper problem which manifests itself as the reversed profile. I am trying to diagnose this when I get time to devote to it, but it will be a bit of a slow process I'm afraid. To assist in this I've written some code to allow full output of the grid point values at any stage in the code. I'll be integrating this with lime and making a pull request shortly. This will make it easier to see what the level populations look like along lines of sight which give this reversed profile. I can't rule out completely a simple sign error but the shifts in line centres if one uses a simple model with uniform v_z components all check out as expected, as does the hyperfine structure of lines which have this, so at this stage my own money is on some deeper error and not on something so simple as a reversed sign.

**Comment by christianbrinch** [comment]
This issue stresses the importance of having a set of benchmark problems to test the code *all the time*.  My private copy which branched off around version 1.4 does not hav this issue.

**Comment by GaryFuller** [comment]
Thanks. I'll be glad to hear when the problem is resolved.

**Comment by imckstewart** [comment]
Christian have you tried adding, say, a constant 1e4 to your velocity z component and seeing which way the line shifts (for theta=phi=0). Benchmark problems and other test sets are great for when the code has moved out of the development (alpha) phase; I do not personally feel that lime has yet reached this status.
