### ISSUE TITLE
Code review telecon

### ISSUE THREAD

**Issue by imckstewart** [lime-rt/lime#89]
I'll be mailing people also about this too, but I don't have everybody's mail address.

I'd like to suggest having a telecon sometime in the next month to discuss where we are going with lime. There are 2 or 3 of us actively submitting code for lime; I know Tuomas Lunttila is working on some fairly major stuff, not yet in a PR, and I have at least 2 more largish PR's planned in the near future. We also have PRs such as Mathieu Westphal's python interface which have been sitting in limbo now for some time. Finally, part of my task at Leiden is also to integrate lime better with a gui wrapper for it which is called Artist. So with all of these bits and pieces in the stew pot I'd suggest it would be good for all parties currently interested in lime development to get together. Probably the best thing is for anyone interested to send me a mail direct at ims at strw dot leidenuniv dot nl. If we can in a first iteration narrow to a period of 2 weeks I can set up a doodle poll.

**Comment by christianbrinch** [comment]
Just to let you know, Sebastien and I will chair a discussion session on LIME at the protoplanetary disk meeting in Edinburgh next month. One of the topics will be the future of the code.
