### ISSUE TITLE
Adding CMB to "reduced" Stokes parameters

### ISSUE THREAD

**Issue by ParfenovS** [lime-rt/lime#94]
It seems like the code adds/subtracts cosmic microwave background to all reduced Stokes parameters (see the traceray procedure). Is that correct?
If it's correct then, probably, one will obtain an incorrect polarisation degree.

**Comment by imckstewart** [comment]
Seems to be the case, yes. Polarisation is one of the many alternatives in lime which I have not yet paid any attention to.

**Comment by smaret** [comment]
Fixed with e9ab5f1.
