### ISSUE TITLE
Line blending doesn't work properly

### ISSUE THREAD

**Issue by tlunttil** [lime-rt/lime#99]
Line blending is supposed to be taken care of with code between lines 257 and 280 in photon.c (main branch). However, the code doesn't seem to work properly. The for-loop starting at line 260 is supposed to go through all blended lines, but because the number of blended lines is calculated incorrectly, the loop body is never run. Parameter matrix is a pointer to struct of type blend, so sizeof(matrix) is on most machines 8 bytes, while sizeof(blend) is (at least) 16 bytes.

The code inside the loop (that is currently never run) also looks a bit suspicious to me. I don't think that the changes due to blending to tau and other parameters are necessarily made to the correct lines.

**Comment by allegroLeiden** [comment]
I had a look at this. The loop maximum is easy to fix, but I think too that there is something screwy about the test `if(matrix[jline].line1 == jline` etc. The comparison should surely be against `iline` not `jline`, and the sign of the addition to `delta` should change depending on whether `.line1` or `.line2` matches `iline`. Maybe something like

    if(matrix[jline].line1 == iline || matrix[jline].line2 == iline){
      if(matrix[jline].line1 == iline)
        blendDV = deltav + matrix[jline].deltav;
      else
        blendDV = deltav - matrix[jline].deltav;

      if(!par->doPregrid)
        calcLineAmpSpline(g,here,dir,g[id].mol[counta[jline]].binv,blendDV,&vblend);

etc.

**Comment by allegroLeiden** [comment]
I note too that the incoming spectrum in line overlap regions is calculated twice, i.e. once for each line. I suppose that makes for the simplest code however. I also don't much like that the line separation at which blending begins to be considered is hard-wired at 10^4. Seems to me it should be some multiple of the maximum Doppler width.

**Comment by tlunttil** [comment]
I agree about the fixed blending threshold. Properly it should be something that depends on the ratio of max velocity separation in the model and max doppler width.

**Comment by tlunttil** [comment]
The blending part is IMO written confusingly. Surely blending should be symmetric, so if line _a_ is blended with line _b_, so is line _b_ blended with line _a_. So we could have a symmetric matrix of zeros and ones where one indicates a (possible) overlap and a corresponding skew-symmetric matrix of line centre velocity differences. To check for blendings with the current `iline`, just find the ones on the _i_th row of the blending matrix. In practice the blending matrix would probably be mostly zeros, so it should be stored "sparsely". Something like this:

`
for (jline=0;jline<num_blends[iline];jline++) {
  int *blend_row = blend_matrix_rows[iline];
  double *deltav_row = deltav_matrix_rows[iline];
  linecentre_deltav=deltav_row[jline];
  calculate blending due to line blend_row[jline]...
}  
`

As an aside: why are `counta` and `countb` redone for each new ray with a call to `lineCount()` near the beginning of function `photon()`? These arrays are the same for each ray, right? Their names are not that descriptive either...

**Comment by tlunttil** [comment]
There's also another problem: currently line blending is completely ignored in function `getjbar()`. It should be included there in the same way as in `photon()`.

**Comment by imckstewart** [comment]
- Yes, yours is the better way re the blending storage. One should be able to test each `iline` just once to see if it is blended with any lines, then just cycle through their number.
- I agree also about the excessive calls to `lineCount()`, I'd noticed this already. And I replaced `counta` etc by more descriptive names already in several of my PRs. :smile:
- I had assumed that `getjbar()` was just multiplying the incoming spectrum (which should include blended lines) by the line shape for the transition of present interest, therefore should itself not include blending; but on further examination of the code I think you are right - the transition line shape is stored in `mp[0].vfac`, the already-blended component in `mp[0].phot`, but added to the latter is the last little contribution from half the working cell, which should include blending.

**Comment by tlunttil** [comment]
It might be worth it to write the blending code in `photon()` and `getjbar()` in a way that allows easy extension to multiple species with overlap possibly also between different species (see #21).

**Comment by imckstewart** [comment]
I've been looking into this, I now have it working as far as the code goes, but in testing it with the lambda methanol file, I see this molecule has a large number of blended lines, of order 10^3. Many of these 'blends' appear to have the exact same frequency. Looping over all of these for every edge for every photon for every grid point for every iteration is going to take the length of a PhD at least. :smile: I wonder whether a better method would be to construct a priori a lookup-table lineshape for every blended set of lines, just to keep the number of inner loop passes within reasonable bounds.

**Comment by tlunttil** [comment]
Hmm, I'd never thought that the number of overlapping lines (or lines in general) could be that high.

Running LIME with a molecule like CH3OH is with the full set of ~2000 radiative transitions given in Lamda is never going to be blazingly fast, with or without blending. However, with the current method computation time scales roughly proportional to the number of lineblends for an average line; for CH3OH this seems to be of order 10. So maybe there's a chance of getting the running time from length of a PhD to  that of a master's thesis project ;)

I'm not sure how the lookup-table lineshape would work; doesn't the lineshape depend on the level populations that are not known _a priori_? There is some unnecessary duplication of effort in the current method, we could reuse a lot of calculations for a set of mutually overlapping lines by doing them "all at once", but it seems to me that this would be rather messy...

**Comment by imckstewart** [comment]
Yeah a lookup table isn't the answer. Realized that while shaving this morning. Oh well I will upload the code I have and see what Sebastien makes of it.

BTW Tuomas, Lime already caters for multiple species in the blending (one of the few areas where this is fully implemented), since in `lineCount()` it makes a master list of all lines from all species.

**Comment by tlunttil** [comment]
Nice work with the new line blending code Ian! 

I guess (haven't tried it yet, though) that a big factor in the slowness of lineblending is the need to recalculate `velocityspline` for each blend. I have a feeling that there's a lot of work there that gets redone several times which could somehow be reused. Not sure how, yet...
